name:                care
version:             0.1.0.0
github:              "Docteur-Lalla/care"
license:             BSD3
author:              "Camille Le Bon"
maintainer:          "camille.lebon35000@gmail.com"
copyright:           "2021 Camille Le Bon"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Programming language inspired by awk for stream processing

dependencies:
- base >= 4.7 && < 5
- containers >= 0.6

library:
  source-dirs: src

executables:
  care-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - care

tests:
  care-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - care
